/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        paper: '#F8F8F6',
        'warm-white': '#FAFAF8',
        ink: '#1A1A1A',
        'deep-ink': '#3A3A3A',
        'soft-ink': '#7A7A7A',
        'light-gray': '#D8D8D8',
        mist: '#ECECEC',
        copper: '#A88756',
        cinnabar: '#8B2E2E',
        jade: '#36463D',
      },
      fontFamily: {
        serif: ['"Noto Serif SC"', 'serif'],
        wenkai: ['"LXGW WenKai"', 'cursive'],
        sans: ['"MiSans"', '"HarmonyOS Sans"', 'system-ui', 'sans-serif'],
        display: ['"Cormorant Garamond"', 'serif'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '1.1', fontWeight: '700' }],
        'hero': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'h1': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'h2': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'h3': ['18px', { lineHeight: '1.4', fontWeight: '500' }],
        'body': ['15px', { lineHeight: '1.6' }],
        'body-sm': ['14px', { lineHeight: '1.6' }],
        'caption': ['13px', { lineHeight: '1.5' }],
        'tiny': ['12px', { lineHeight: '1.4' }],
      },
      borderRadius: {
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '20px',
        'xl': '24px',
        '2xl': '28px',
        '3xl': '32px',
      },
      boxShadow: {
        'paper-sm': '0 1px 3px rgba(0,0,0,0.02)',
        'paper-md': '0 4px 6px rgba(0,0,0,0.04)',
        'paper-lg': '0 10px 15px rgba(0,0,0,0.06)',
        'ink-sm': '0 1px 2px rgba(26,26,26,0.04)',
        'ink-md': '0 4px 8px rgba(26,26,26,0.06)',
        'ink-lg': '0 8px 24px rgba(26,26,26,0.08)',
      },
      spacing: {
        'ink-1': '8px',
        'ink-2': '12px',
        'ink-3': '16px',
        'ink-4': '20px',
        'ink-5': '24px',
        'ink-6': '32px',
        'ink-7': '40px',
        'ink-8': '48px',
        'ink-9': '64px',
        'ink-10': '96px',
        'ink-11': '128px',
      },
      keyframes: {
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'ink-spread': {
          '0%': { transform: 'scale(0)', opacity: '0.6' },
          '100%': { transform: 'scale(1)', opacity: '0' },
        },
        'breathe': {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
        'shake': {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%': { transform: 'translateX(-4px)' },
          '40%': { transform: 'translateX(4px)' },
          '60%': { transform: 'translateX(-2px)' },
          '80%': { transform: 'translateX(2px)' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.5s ease-out',
        'ink-spread': 'ink-spread 4s ease-out infinite',
        'breathe': 'breathe 4s ease-in-out infinite',
        'shake': 'shake 0.4s ease',
      },
    },
  },
  plugins: [],
};
